### ISSUE TITLE
It would be super cool if you could make a step by step tutorial on how to train the model on new datasets. :)

### ISSUE THREAD

**Issue by Christoph-Schuhmann** [sayakpaul/A-Barebones-Image-Retrieval-System#1]
It would be super cool if you could make a step by step tutorial on how to train the model on new datasets. :)

I would like to use your technique to sort unlabled images into different domains, which then could be used to train GANs to create images of these domains.

**Comment by sayakpaul** [comment]
@Christoph-Schuhmann thank you for your interest. I plan to either write a tutorial or put together a deck. 

For now, [this notebook](https://github.com/sayakpaul/A-Barebones-Image-Retrieval-System/blob/master/FaceNet_Like_Less_BiT.ipynb) could be useful.
